language: php
php:
- 7.1.3
before_script:
- composer self-update
- composer install --prefer-source --no-interaction
- echo $SPORTMONKS_API_TOKEN
script:
- vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
- bash <(curl -s https://codecov.io/bash)
